services:
  app:
    build:
      context: .
    image: karan1989/karan-trailquest:local
    container_name: karan-trailquest-app
    env_file:
      - .env
    environment:
      ENVIRONMENT: docker-compose
    ports:
      - "5000:5000"
    restart: unless-stopped
