apiVersion: apps/v1
kind: Deployment
metadata:
  name: karan-trailquest-app
  namespace: karan-trailquest
  labels:
    app: karan-trailquest
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: karan-trailquest
  template:
    metadata:
      labels:
        app: karan-trailquest
    spec:
      containers:
        - name: karan-trailquest
          image: IMAGE_REPOSITORY_PLACEHOLDER:IMAGE_TAG_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          envFrom:
            - configMapRef:
                name: karan-trailquest-config
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: karan-trailquest-secret
                  key: MONGO_URI
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 8
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
