apiVersion: v1

kind: ConfigMap

metadata:

  name: karan-dashboard-config

  namespace: karan-dashboard

data:

  APP_NAME: "Karan DevOps Dashboard"

  APP_VERSION: "3.0.0"

  ENVIRONMENT: "kubernetes"

  MONGO_DB_NAME: "karan_dashboard"
